images:
- name: quay.io/suchugh/product-catalog/server
  newName: quay.io/suchugh/product-catalog/server
  newTag: test
- name: quay.io/sumiranchugh/product-catalog/server
  newName: quay.io/sumiranchugh/product-catalog/server
  newTag: f08be80-110331912
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
