generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/part-of: product-catalog

configMapGenerator:
- name: productdb-init
  files:
    - config/90-init-database.sh
    - config/import.sql
    - config/schema.sql

resources:
  - db-pvc.yaml
  - db-secret.yaml
  - db-service.yaml
  - db-deployment.yaml