apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: server-post-prod
spec:
  workspaces:
    - name: newman-env
    - name: slack-secret
      optional: true
  tasks:
    - name: prod-test
      taskRef:
        name: newman
      params:
        - name: COLLECTION
          value: https://raw.githubusercontent.com/sleazyslazy/product-catalog-server/master/tests/product-catalog-server-tests.json
        - name: ENVIRONMENT
          value: newman-prod-env.json
      workspaces:
        - name: newman-env
          workspace: newman-env
