resources:
- ../../base

images:
- name: quay.io/suchugh/product-catalog/client
  newName: quay.io/suchugh/product-catalog/client
  newTag: 7fe145d-2d1WFqrLx3jZnPTwGm9DaY5zMIQ
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
