---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dest-docker-config
  namespace: product-catalog-cicd
spec:
  encryptedData:
    .dockerconfigjson: AgAgBuCRLzA/fGCchshI8wE0NcVdvP8q9ihORgpY6onmLrbl+lWk7viPsBHvs56fFj/1GhwpMcJVsHtK8MatLGwf1f6U40RqCHpsz4j8eCAwRaRL4bD6Sx7XBbQcNtBVHxT11q2GCpuj1XoSAmiVLBklfhteg8Y0y4EL67ZBVy5cvFK49LtbJStQHH/de8PQSoE/CaJgScovFRV77srt675OBS5+3JgQkO5rYN88vn+Nz5Yy/8uYgjJmy4MGEjm6WE3MbkIZL0CrDtqI765p2T6NaDF4sUzEypHWhsEsGB7tufViVJegPat8mnAhPGCWrXhNSaDFmrMArCbTfGvi5qz5AnvbtsKFAyZ/GFPR++W1KHZ2FRGrn1AgSq0aZajtchH38eHo299haJbNbGkC6lpYlpGcSuc/RDAzYfohJs+ullwqnTYcIK/mCchB3kHsE1CSC10bsoPDNLXesonlusKkU/xOQcfjQz2Anobdklo5Tn14D94kV6L1nNJd0G/RTUW6Nnf4xX8zOjYyMb1u4U+zOyThnQjuBqeARXmXRut72xuGyG/nnx9/5fv0xFuVX4lIgwh0OdGuBUp1oCcpMbfo4v8bS12aksyQGb6HtIrCZI5KakGPjVC9vZxC7Gw+zrVNZMZZ+96l7mSBZCsVCRSczmleH7qmMVBZAy0opBNM5Rq7bT5zOpOYblAuIBjy2BYoE1AGHt45xmywklJIsxhvGA9C62hK+30O4du/b3CQncHChlszadQZB4up9k4x79EiJG0CN0jbShkWMjP8z+Srs5TWbSRf5vrL3fzNz6gQIUVyY8SuqTBGJvJ6TFSl06YlVR/VOCe8kHIyNoH4Xn+FYRGOvnOdnLcp8VbILIQG0E7xPQb9il30gPD5qKfFW9mo6FeDCwa/TKZx3w18grDNxXmJJGUgUIzCzizjppqbb3G8Q34Dlv4pAIf0
  template:
    metadata:
      creationTimestamp: null
      name: dest-docker-config
      namespace: product-catalog-cicd
    type: kubernetes.io/dockerconfigjson
