apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: product-catalog-cicd

resources:
- workspace-template-cm.yaml
- gitops-network-policy.yaml
- github-sealed-secret.yaml
- ../../../components/tekton/tasks/base
- ../../../components/tekton/pipelines/client/base
- ../../../components/tekton/pipelines/server/base
- ../../../components/tekton/pipelines/push-prod-pr/base
- ../../../components/tekton/triggers/base
- setup-local-credentials-job.yaml
- prod-network-policy.yaml
- dockerconfig-sealed-secret.yaml