resources:
- ../../base

images:
- name: quay.io/suchugh/product-catalog/client
  newName: quay.io/suchugh/product-catalog/client
  newTag: test
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
