apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: client
spec:
  workspaces:
    - name: git-source
    - name: gitops-manifests
  params:
    - name: source_git_revision
      type: string
      default: master
    - name: source_git_url
      type: string
      default: https://github.com/sleazyslazy/product-catalog-client
    - name: gitops_git_revision
      type: string
      default: main
    - name: gitops_git_url
      type: string
      default: https://github.com/sleazyslazy/product-catalog
    - name: image_dest_url
      type: string
      description: External registry location to copy image to
      default: quay.io/suchugh/product-catalog
    - name: cluster
      type: string
      description: Cluster to push to
      default: "dev"
    - name: sonarqube_host
      default: sonarqube-sonarqube.apps.cluster-26j82.dynamic.redhatworkshops.io
      description: Where sonarqube is located to support project scanning
  tasks:
    - name: clone
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: git-source
      params:
        - name: url
          value: "$(params.source_git_url)"
        - name: revision
          value: "$(params.source_git_revision)"
        - name: deleteExisting
          value: "true"
    - name: clone-gitops-manifests
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: gitops-manifests
      params:
        - name: url
          value: "$(params.gitops_git_url)"
        - name: revision
          value: "$(params.gitops_git_revision)"
        - name: deleteExisting
          value: "true"      
    - name: generate-id
      taskRef:
        kind: Task
        name: generate-build-id
      runAfter:
        - clone
      workspaces:
        - name: source
          workspace: git-source
    - name: build
      taskRef:
        name: npm
        kind: Task
      runAfter:
        - generate-id
      workspaces:
        - name: source
          workspace: git-source
    - name: quality
      taskRef:
        name: npm-quality
        kind: Task
      runAfter:
        - build
      workspaces:
        - name: source
          workspace: git-source
    - name: build-image
      taskRef:
        name: buildah
        kind: Task
      workspaces:
        - name: source
          workspace: git-source
      runAfter:
        - quality
      params:
      - name: IMAGE
        value: $(params.image_dest_url):latest
      - name: DOCKERFILE
        value: ./Containerfile
    - name: tag-dev-image
      taskRef:
        name: push-image
        kind: Task
      runAfter:
        - build-image
      params:
        - name: src_image
          value: $(params.image_dest_url)@$(tasks.build-image.results.IMAGE_DIGEST)
        - name: dest_image
          value: $(params.image_dest_url)
        - name: dest_tags
          value: $(tasks.generate-id.results.tag_id),dev
    - name: dev-update-image
      taskRef:
        name: update-image
        kind: Task
      runAfter:
        - clone-gitops-manifests
        - tag-dev-image
      params:
        - name: git_revision
          value: "$(params.gitops_git_revision)"
        - name: path
          value: components/apps/client/overlays/$(params.cluster)
        - name: image
          value: "$(params.image_dest_url)"
        - name: image_tag
          value: $(tasks.generate-id.results.tag_id)
      workspaces:
        - name: gitops-manifests
          workspace: gitops-manifests
    - name: dev-gitops-deploy
      taskRef:
        kind: ClusterTask
        name: argocd-task-sync-and-wait
      runAfter:
        - dev-update-image
      params:
        - name: application-name
          value: client-dev
        - name: revision
          value: $(params.gitops_git_revision)
        - name: deployment
          value: client
        - name: namespace
          value: product-catalog-dev
        - name: image-tag
          value: $(tasks.generate-id.results.tag_id)
        - name: flags
          value: "--insecure"
        - name: argocd-version
          value: v2.9.5  
    - name: tag-test-image
      taskRef:
        name: push-image
        kind: Task
      runAfter:
        - dev-gitops-deploy
      params:
        - name: src_image
          value: $(params.image_dest_url)@$(tasks.build-image.results.IMAGE_DIGEST)
        - name: dest_image
          value: $(params.image_dest_url)
        - name: dest_tags
          value: $(tasks.generate-id.results.tag_id),test,latest
    - name: test-update-image
      taskRef:
        name: update-image
        kind: Task
      runAfter:
        - tag-test-image
      params:
        - name: git_revision
          value: "$(params.gitops_git_revision)"
        - name: path
          value: clusters/$(params.cluster)/overlays/test
        - name: image
          value: "$(params.image_dest_url)"
        - name: image_tag
          value: $(tasks.generate-id.results.tag_id)
      workspaces:
        - name: gitops-manifests
          workspace: gitops-manifests
    - name: test-gitops-deploy
      taskRef:
        kind: ClusterTask
        name: argocd-task-sync-and-wait
      runAfter:
        - test-update-image
      params:
        - name: application-name
          value: product-catalog-test
        - name: revision
          value: $(params.gitops_git_revision)
        - name: deployment
          value: client
        - name: namespace
          value: product-catalog-test
        - name: image_tag
          value: $(tasks.generate-id.results.tag_id)
