apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: product-catalog-dev

bases:
- cicd-networkpolicy.yaml
- ../../../components/apps/database/base
- ../../../components/apps/client/overlays/dev
- ../../../components/apps/server/overlays/dev

